# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-13 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbapp', '0004_auto_20190613_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultrecord',
            name='delete_status',
        ),
    ]
