# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-17 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbapp', '0006_auto_20190614_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_menus',
            field=models.BooleanField(default=False),
        ),
    ]
