# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-18 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbapp', '0008_auto_20190618_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(to='nbapp.ClassList', verbose_name='已报班级'),
        ),
    ]
